### backgrounds configuration
output * bg ~/.config/sway/current_wallpaper fill

default_border none
gaps inner 5
gaps outer 5
smart_gaps off
# Custom opacity
for_window [app_id=".*"] opacity 0.9
for_window [class=".*"] opacity 0.9
